apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    {{- include "my-app.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.app.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: my-app
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        {{- include "my-app.labels" . | nindent 8 }}
      {{- if .Values.metrics.enabled }}
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: {{ .Values.port | quote }}
        prometheus.io/path: "/-/metrics"
      {{- end }}
    spec:
      dnsPolicy: {{ .Values.dnsPolicy }}
      {{- if .Values.seed.enabled }}
      initContainers:
        - name: seed
          image: "{{ .Values.app.image.repository }}:{{ .Values.app.image.tag }}"
          command: ["/entrypoint.sh", "seed"]
          env:
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.cnpg.clusterName }}-app
                  key: host
            - name: DB_PORT
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.cnpg.clusterName }}-app
                  key: port
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.cnpg.clusterName }}-app
                  key: dbname
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.cnpg.clusterName }}-app
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.cnpg.clusterName }}-app
                  key: password
            - name: MY_APP_POSTGRES_URL
              value: "postgres://$(DB_USER):$(DB_PASSWORD)@$(DB_HOST).{{ .Values.cnpg.namespace }}:$(DB_PORT)/$(DB_NAME)"
            - name: MY_APP_POSTGRES_SCHEMA
              value: {{ .Values.postgresql.schema }}
            {{- if $.Values.optimizeForMemorySize }}
            - name: OPTIMIZE_FOR_MEMORY_SIZE
              value: "true"
            {{- end }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.app.image.repository }}:{{ .Values.app.image.tag }}"
          imagePullPolicy: {{ .Values.app.image.pullPolicy }}
          env:
            {{- $origin := .Values.origin }}
            {{- if not $origin }}
              {{- if and .Values.ingress.enabled .Values.ingress.host }}
                {{- $origin = printf "https://%s" .Values.ingress.host }}
              {{- end }}
            {{- end }}
            {{- if $origin }}
            - name: ORIGIN
              value: {{ $origin }}
            {{- end }}
            {{- if .Values.oidc.enabled }}
            - name: AUTHELIA_ISSUER
              value: {{ .Values.oidc.issuer }}
            - name: AUTHELIA_CLIENT_ID
              value: {{ .Values.oidc.clientId }}
            - name: AUTHELIA_CLIENT_SECRET
              value: {{ .Values.oidc.clientSecret }}
            {{- end }}
            {{- if .Values.adminToken }}
            - name: MY_APP_ADMIN_TOKEN
              value: {{ .Values.adminToken }}
            {{- end }}
            {{- if .Values.smtp.host }}
            - name: SMTP_HOST
              value: {{ .Values.smtp.host }}
            - name: SMTP_PORT
              value: {{ .Values.smtp.port | quote }}
            - name: SMTP_USER
              value: {{ .Values.smtp.user }}
            - name: SMTP_PASS
              value: {{ .Values.smtp.pass }}
            - name: EMAIL_FROM
              value: {{ .Values.smtp.from }}
            {{- end }}
            {{- if .Values.smtp.testTo }}
            - name: TEST_EMAIL_TO
              value: {{ .Values.smtp.testTo }}
            {{- end }}
            {{- if .Values.optimizeForMemorySize }}
            - name: OPTIMIZE_FOR_MEMORY_SIZE
              value: "true"
            {{- end }}
            {{- if .Values.nodeOptions }}
            - name: NODE_OPTIONS
              value: {{ .Values.nodeOptions }}
            {{- end }}
            {{- if .Values.nodeTLSRejectUnauthorized }}
            - name: NODE_TLS_REJECT_UNAUTHORIZED
              value: "0"
            {{- end }}
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.cnpg.clusterName }}-app
                  key: host
            - name: DB_PORT
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.cnpg.clusterName }}-app
                  key: port
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.cnpg.clusterName }}-app
                  key: dbname
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.cnpg.clusterName }}-app
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.cnpg.clusterName }}-app
                  key: password
            - name: MY_APP_POSTGRES_URL
              value: "postgres://$(DB_USER):$(DB_PASSWORD)@$(DB_HOST).{{ .Values.cnpg.namespace }}:$(DB_PORT)/$(DB_NAME)"
            - name: MY_APP_POSTGRES_SCHEMA
              value: {{ .Values.postgresql.schema }}
          ports:
            - name: http
              containerPort: {{ .Values.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /-/healthy
              port: http
            initialDelaySeconds: 10
            periodSeconds: 15
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /-/ready
              port: http
            initialDelaySeconds: 10
            periodSeconds: 15
            failureThreshold: 3
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
