apiVersion: v2
name: my-app
description: A Helm chart for my-app
type: application
version: 0.1.1
appVersion: latest
home: https://github.com/users/stephane-klein/packages/container/package/charts%2Fmy-app
sources:
  - https://github.com/stephane-klein/my-app
