services:
  authelia:
    image: authelia/authelia:latest
    container_name: authelia-test
    restart: unless-stopped
    ports:
      - 9091:9091
    environment:
      TZ: UTC
    volumes:
      - ./configuration/configuration.yml:/config/configuration.yml
      - ./configuration/users.yml:/config/users.yml
      - ./secrets/:/config/secrets:ro
      - authelia_data:/data
    depends_on:
      redis:
        condition: service_started
    networks:
      - authelia-net

  redis:
    image: redis:7-alpine
    container_name: authelia-redis-test
    restart: unless-stopped
    networks:
      - authelia-net

volumes:
  authelia_data:

networks:
  authelia-net:
    driver: bridge
